### ISSUE TITLE
Disabled Button bug

### ISSUE THREAD

**Issue by 332lfgb6** [Spiderpig86/Cirrus#117]
The documentation states that div buttons are not supported, but I found that the buttons created by the A tag are not supported either
![image](https://user-images.githubusercontent.com/51245335/171683686-b7d336dd-f78e-42c4-bbc9-3e5ca517cbd0.png)
![image](https://user-images.githubusercontent.com/51245335/171683762-7ae34715-2e90-4be1-878b-e763311387d8.png)
![image](https://user-images.githubusercontent.com/51245335/171684399-94cb8609-ffd7-40d3-9397-452b22cdabba.png)
```html
<button class="btn-primary" disabled>Button</button>
    <div class="btn btn-primary" disabled>Button</div>
    <input class="btn-primary" type="submit" value="Submit" disabled />
    <a href="https://www.bing.com/" class="btn btn-primary" disabled>Button</a>
```

**Comment by Spiderpig86** [comment]
Thanks for the bug report! I will take a look at this soon.

**Comment by Spiderpig86** [comment]
I took a look to see why the disabled attribute doesn't work for the `a` or `div` tags. This is because the `disabled` attribute is [not supported](https://www.w3.org/TR/html4/index/attributes.html#:~:text=directionality-,disabled,-BUTTON%2C%20INPUT) for those tags.

As an alternative, I added a `btn--disabled` class to simulate the disabled state for `a` and `div` tags.
