### ISSUE TITLE
footer-list-item style not applied properly

### ISSUE THREAD

**Issue by TungDoanDuong** [Spiderpig86/Cirrus#12]
Hi, found your framework yesterday and I very like it. I'm using it in a project right now, but for the footer, I noticed that the red box that surround the item does not surround it like in the documentation.

I copied to the footer from the documentation and this is what I see

![screen shot 2018-09-02 at 1 35 49 pm](https://user-images.githubusercontent.com/10658428/44958923-2b165e80-aeb5-11e8-8641-f4bcdc645e61.png)

with this code (react):
`
<a href='#'
    <li className='footer-list-item>Home</li>
</a>
`

I even tried putting with `class='list-item'` and still the same problem.

Is it something wrong with my writing or it's the framework?

FYI, I'm using the package from this CDN: `https://cdn.jsdelivr.net/npm/cirrus-ui@0.5.4/dist/cirrus.min.css`

Thanks

**Comment by Spiderpig86** [comment]
Glad to hear you liked it!
Anyway, the issue has been fixed in https://github.com/Spiderpig86/Cirrus/commit/a049d802c9e026bcb7f4a6fa5e5114ba5abe9b08 where the `display` of the link was not set to `block` so it would properly wrap around the text.

Adding `display: block` to your links in the CSS file should fix the issue.

This fix is already included in the next version of Cirrus.

**Comment by TungDoanDuong** [comment]
oh simple as that haha
Thanks!
