### ISSUE TITLE
Margin /  padding viewport 'xs' doesn't exist

### ISSUE THREAD

**Issue by Rainfellow2002** [Spiderpig86/Cirrus#148]
The viewport 'xs' doesn't seem to exist for margin or padding (only sm, md, lg, xl). The following doesn't work:

`<div class="m-10-xs"><p>This is a test</p></div>`

**Comment by Spiderpig86** [comment]
Hi @Rainfellow2002 , could you please update the code sample? It doesn't include the classes you say are missing. Looking at the source, `m-1-xs` would be redundant since it acts the same as `m-1` today. For example, `m-1-sm` means `m-1` applies to viewports `sm` and larger. You can read more about this [here](https://www.cirrus-ui.com/fundamentals/viewports).

**Comment by Rainfellow2002** [comment]
Hi @Spiderpig86, thanks for your quick reply. Ah now i get it, one have to keep mobile-first in mind.
It is also described thoroughly in [Usage](https://www.cirrus-ui.com/fundamentals/viewports#usage) section of the page you mentioned.
Keep up the good work, love this lightweight framework!
