### ISSUE TITLE
Better documentation on simple Menu List

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#198]
The doc on https://cirrus-ui.netlify.app/elements/lists#menus has a demo with simple menu list, but no code example is given. When I try this, it's surprised me that what's described is not enough to get the selected row to be highlighted.

What I mean is the following will not have selected item displayed:
```
<ul class="menu">
   <li class="menu-item">Google Chrome</li>
   <li class="menu-item selected">Firefox</li>
   <li class="menu-item">Polarity</li>
</ul>
```

User must use `<a>` to see the selected usage. I suggest either documentation should mention this, or better yet, make `<a>` not a requirement, so user can use `<span>` or `<div>` in case where the menu item does not go to another page url, but simply handle user click event.

**Comment by Spiderpig86** [comment]
I will be updating this component so that the `a` tag is no longer required. The following is what we should expect where the top is for a regular list for any element and the bottom has the anchor tag embedded inside the list item.

![image](https://github.com/Spiderpig86/Cirrus/assets/2801187/e6bfeedf-32a3-47da-956c-38f27d409362)

**Comment by Spiderpig86** [comment]
This has been updated to go back to the old model where the `menu-item` doesn't contain the main styling, but the child elements do (e.g. `a` and now `span` and `div`). This is so we can continue supporting nested lists.
![image](https://github.com/Spiderpig86/Cirrus/assets/2801187/8a1339c4-0e94-468e-a10d-3514d7c3b5a7)
