### ISSUE TITLE
How can I open modal with a class name?

### ISSUE THREAD

**Issue by zemian** [Spiderpig86/Cirrus#203]
Hi, I have couple of issues to ask regarding modal usage:

1) Is there reason I can't get the "Basic Dialog" example code working as mentioned in the [doc](https://cirrus-ui.netlify.app/elements/modal#basic)? 
See https://codepen.io/zemian/pen/XWomVzN

2) Is there a class we can use to open the Modal instead of using `<a href="#">`? This is not a good way when using other JS that we do not want to modify the URL. It is much preferred to have a CSS class to activate modal instead.

**Comment by zemian** [comment]
Oh just found `modal—visible` class. Please update docs!

**Comment by Spiderpig86** [comment]
1) This doesn't work because the link in `<a href="#test-modal">Open Modal</a>` is references an HTML element with the id of `test-modal` when it doesn't exist. Your modal is still defined with an id of `basic-modal`. You can find out more about this in this part of the [docs](https://www.cirrus-ui.com/elements/modal#modals:~:text=on%20a%20prompt.-,Opening%20a%20Modal,-To%20open%20a)

2) Yup, that is a new class. Will update the docs.

**Comment by Spiderpig86** [comment]
This was updated in commit 70ffb04, closing.
