### ISSUE TITLE
class="text-left" in TD gets ignored

### ISSUE THREAD

**Issue by smavridis** [Spiderpig86/Cirrus#26]
First of all, thank you for creating Cirrus, it really improved the look of my project with little fuss.

I am trying to left align a specific cell in a table.
To do that i just added the 'text-left' class:

`<td class="text-left">.org.chromium.Chromium.GhfJ0n</td>`

This did not work however.
Looking into it, it appears the `.table td` rules set `text-align: inherit;` and this leads to the `.table` setting to be applied, instead of the `.text-left` i wanted. 

Is that the intended behavior?

Removing the `text-align: inherit;` from `.table td` results it (my) expected result with the left-aligned text. I took a picture to show what i am saying ( https://ibb.co/VJZR05R )

Aside from modifying the Cirrus code, how could i resolve this?

**Comment by Spiderpig86** [comment]
Hi! 👋 

Thanks for checking out my framework and glad to hear that it has helped. Looking at the gif, it seems that you are using an outdated version of Cirrus since `text-left` has been renamed to `u-text-left`. 

Anyway, based on my understanding, it seems that the `.table td` class overrides more generic classes assigned to any element, hence why it doesn't work. I'll push out a small update to add the `!important` keyword to these modifier classes. I think I accidentally removed a lot of them since they were usually considered a bad practice on non-modifiers.

Will be pushing out an update soon, thanks for the report! 👍

**Comment by Spiderpig86** [comment]
This is now fixed with commit 0c939de262707cb8e7a746d0622cba8190ca7312. The update will be released with 0.5.6, but you can get the latest version inside the `dist` folder.
