### ISSUE TITLE
Button Groups not rounding correct corners at certain view widths.

### ISSUE THREAD

**Issue by atclarkson** [Spiderpig86/Cirrus#30]
When screen is tablet or desktop width and the buttons are stacked, all in a column or 2 buttons over 1 button, the wrong corners are rounded. This takes away the seamless effect that was desired.

It looks like the first button of group always rounds the left side of button and the last button always rounds the right side.

![Screen Shot 2020-03-11 at 8 23 31 AM](https://user-images.githubusercontent.com/1444442/76416529-a3df5c00-6371-11ea-9510-b6b2a91ebb4b.png)

![Screen Shot 2020-03-11 at 8 23 44 AM](https://user-images.githubusercontent.com/1444442/76416533-a641b600-6371-11ea-87d5-67ed98b2be64.png)

**Comment by Spiderpig86** [comment]
Thanks for the info! This has been rectified as of commit cc11f373016ed95aa8194b936f72aeb1b33126b3.

![image](https://user-images.githubusercontent.com/2801187/76499093-5ad3ea00-63fb-11ea-93ff-447f5ef011d7.png)

The prior button layout was too complicated to fix since the rounding really depended on how many buttons were next to each other on a smaller screen, so a column layout was used instead.
