### ISSUE TITLE
Utility classes not working

### ISSUE THREAD

**Issue by Thijs5** [Spiderpig86/Cirrus#65]
Some utility classes are not working. The problem is in the generated css. Property values are wrapped with quotes while they shouldn't.
https://github.com/Spiderpig86/Cirrus/blob/8e9bbf43a1a1fcd1fa5238e3d68bf46707a300da/dist/cirrus.css#L8079-L8095

**Comment by Spiderpig86** [comment]
Thanks for the report! Looks like this was missed since I only tested against `cirrus.min.css`. Again, highly recommend if you use the minified version if possible. https://github.com/Spiderpig86/Cirrus/blob/8e9bbf43a1a1fcd1fa5238e3d68bf46707a300da/dist/cirrus.min.css You can also use the CDNs on JSDelivr or Unpkg.

I will fix this in a patch release 0.6.2.1.

**Comment by Spiderpig86** [comment]
Resolved with the release of [0.6.2-patch-1](https://github.com/Spiderpig86/Cirrus/releases/tag/0.6.2-patch-1).
