### ISSUE TITLE
Dropdown right-aligned not working on mobile

### ISSUE THREAD

**Issue by Randerspl** [Spiderpig86/Cirrus#67]
**Describe the bug**
Hello, i found that dropdown with right align is not working properly when screen is small (mobile or small window).
I think dropdown should align to right but is aligned to left.
I don't know if this is intentional bahaviour on mobile.

Image from docs as example (small window on PC, on mobile looks same)
![wrongAlign](https://user-images.githubusercontent.com/9450923/125623997-7135f524-49ca-484d-8107-19c2970199d0.png)

And i found propably a typo in docs: i think red text should be _dropdown-right_ instead of _menu-right_  as shown on image below.
![typo](https://user-images.githubusercontent.com/9450923/125623107-c2570058-038a-4689-93e6-5941509815f3.png)

**To Reproduce**
For example enter cirrus [doc page](https://cirrus-ui.netlify.app/components/lists#dropdown) on mobile/small window and scroll to dropdown-right example.
On PC you can adjust window size and see that _dropdown-right_ is aligned to left

**Comment by Randerspl** [comment]
I want to withdraw my bug issue of not aligning because i found error in my code.
I will leave it open because of second issue with documentation.

**Comment by Spiderpig86** [comment]
Thanks for the report and glad you fixed the first issue! The second issue is fixed. I appreciate all the documentation corrections since it helps improve the developer experience for all of us :) and help fix the things that I may have missed.

Fix released with commit https://github.com/Spiderpig86/Cirrus/commit/6e38bd689ff04221faef8849ca30fb0e56b89f81.
