### ISSUE TITLE
Chore: add the u- prefix everywhere

### ISSUE THREAD

**Issue by roonie007** [Spiderpig86/Cirrus#79]
**Is your feature request related to a problem? Please describe.**
It's a little bit disturbing to have some classes with the prefix `u-` and others without it.
I have used Quasar for several years, and everything is prefixed with `q-` and it's great.

**Describe the solution you'd like**
Add the `u-` prefix to every class

**Comment by Spiderpig86** [comment]
Thanks for the suggestion! This would be a large breaking change for the framework. The purpose of the `u-` prefix is to denote that a class is a utility rather than a standard type of class. I was thinking to maybe just remove the `u-` prefix all together if it doesn't add any value. A change like this would have to go in in version `0.7.0` as it would impact many projects.

**Comment by Spiderpig86** [comment]
True, it could conflict with other libraries. But the alternative is to ask existing users to rewrite all their classes with an extra prefix which can be a lot of work. I don't think there is a need to rush this change in the immediate future.
