### ISSUE TITLE
slightly jittery scroll and animations on mobile browsers

### ISSUE THREAD

**Issue by onettmecha** [Spiderpig86/Cirrus#85]
**Describe the bug**
hello, i just started using this framework and i couldn't help but notice the following (on mobile):
- header/nav-bar animation when scrolling downward or upward from stagnant position is slightly jittery.
- page stutters while scrolling down or up at random times.

i tried this on latest versions of:
- firefox
- chrome
- vivaldi

**To Reproduce UX**
since the problem/bug is more user experience than technical then:
- open a mobile browser of your choosing
- visit one or all of the following sites:
       * https://cirrus-ui.netlify.app
       * http://polarity.x10.mx/browser/

after that the steps to reproduce the behavior are:
1. start scrolling down slowly and keep an eye on the header/nav-bar in anticipation for an animation and you should notice the stutter (if not, do it a couple of times).
2. scroll down or up in a swipe motion, meaning do one swipe up or down and let the page scroll for itself, you should see the stutter (if not, do it a couple of times).

**Comment by Spiderpig86** [comment]
Hi!

Thanks for reporting this issue. I tried to reproduce it on mobile and cannot get the same jittery experience with the navbar. The only thing I can think of is due to how different phones perform when rendering CSS. For example, CSS blur effects using `backdrop-filter: blur(2px);` could decrease performance on certain hardware. I don't think there is much that could be done for this issue as CSS rendering/performance is largely dependent on browser and hardware.
