### ISSUE TITLE
Please add infinite scroll pagination 

### ISSUE THREAD

**Issue by jet10000** [Spiderpig86/Cirrus#86]
Please add infinite scroll pagination, now a very common mode on mobile

**Comment by Spiderpig86** [comment]
Thanks for the suggestion! Since Cirrus is a CSS framework and infinite scrolling is usually powered by JavaScript/TypeScript and not CSS.

Also for future reference, please open feature requests following this [template](https://github.com/Spiderpig86/Cirrus/blob/master/.github/ISSUE_TEMPLATE/feature-request.md). Closing.
