### ISSUE TITLE
table Viewports

### ISSUE THREAD

**Issue by bestisben-xyz** [Spiderpig86/Cirrus#90]
**Is your feature request related to a problem? Please describe.**
First thanks alot for providing the css framework, it really help me a lot and really helpful to a beginner^^
However when I wanna to use the table Components, I find out it really not friendly with small screen.
**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/90732027/147263262-67f71996-6436-4c6b-ad01-b47db6b132af.png)
When the table with few data is fine.

![image](https://user-images.githubusercontent.com/90732027/147263348-132d1362-841c-4c12-93ab-027ec2a735d7.png)
When the table with lots of info then the screen become "unclean"

![image](https://user-images.githubusercontent.com/90732027/147263848-0ce7f079-d0af-47e7-acd2-9e14d06a9591.png)
I wish the table would be possible display in this layout with css only

**Comment by Spiderpig86** [comment]
Hi!

Thanks for the suggestion! This is true that tables can get a bit messy with lots of elements, especially with smaller devices. I don't necessarily agree with moving all columns to rows since that would not really be a good UI experience as we would have a whole set of columns for each row. What I think would be better would be to add a new table wrapper class that allows for displaying many columns. It would appear like this:

![image](https://user-images.githubusercontent.com/2801187/147436360-44dd76b2-160d-46f5-b222-0a4fe649582a.png)

**Comment by bestisben-xyz** [comment]
Hi,
Thanks for reply, yeah I agree with you that will be better, wrapper class will not extend outside the bound right?
This is good I think:
![image](https://user-images.githubusercontent.com/90732027/147866531-7e0bf778-8c8a-4be1-bbc9-e3f0cee97fa1.png)

this is not good I think:
![image](https://user-images.githubusercontent.com/90732027/147866539-0fe77e02-45ae-4b9f-9ca3-66d7d1abe5fb.png)

**Comment by Spiderpig86** [comment]
Yes the wrapper class should take the width of the parent div. However if the column widths inside the table exceed the width of the parent, the horizontal overflow will appear.

**Comment by Spiderpig86** [comment]
Added in 0.7.0, closing.
